import { SignInButton , SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { RouterOutputs, api } from "~/utils/api";

import * as dayjs from 'dayjs'
import relativeTime from "dayjs/plugin/relativeTime";


const CreatePostWizard = () => {

  const {user} = useUser();

  if (!user) return null;

  return (
    <div className="flex gap-3 w-full mt-5 p-3">
      <Image src={user.profileImageUrl} className="w-14 h-14 rounded-full" width={100} height={100}  alt="Profile Image"/>
      <input placeholder="Type a Post..." className="bg-transparent grow outline-none"></input>
    </div>
  )

}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props : PostWithUser) => {

  const {post, author} = props;

  return (
    <div key={post.id} className="flex flex-row gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 mt-5">
      <Image src={author.profilePictureUrl} className="w-14 h-14 rounded-full" width={100} height={100}  alt="Profile Image"/>
      <div>
        <section className="flex">
          <h3 className="text-slate-400">@{author.name} </h3>
        </section>
        <div className="text-lg">{post.content}</div>
      </div>
    </div>
  )

}


const Home : NextPage = () => {

  const user = useUser();

  const {data, isLoading} = api.posts.getAll.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Error</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full md:max-w-2xl border-x border-slate-400 p-4">
          {user?.isSignedIn && <CreatePostWizard/>}
          <div>
              {data?.map((fullpost) => ( 
                <PostView {...fullpost} key={fullpost.post.id}/>
              ))}
            </div>

        </div>

      </main>
    </>
  );
}

export default Home;

